### ISSUE TITLE
Property 'startPayload' does not exist on type 'TelegrafContext' in Typescript

### ISSUE THREAD

**Issue by ludusrusso** [telegraf/telegraf#1052]
**Is your feature request related to a problem? Please describe.**
When I call my bot with a /start command I also get a `startPayload` value in the bot context. However, it is not present in types, so I get the `Property 'startPayload' does not exist on type 'TelegrafContext'.` from typescript.

I simply solved it by using `(ctx as any)['startPayload']`, but it would be nice to add it the the ctx types definition

**Describe the solution you'd like**

This code should compile in Typescript

```
import { Telegraf } from 'telegraf';

const token = process.env.TOKEN;

const bot = new Telegraf(token);
bot.start((ctx) => {
 const paylaod = ctx.startPayload
  ctx.reply(startPayload);
});
bot.launch();
```
And then call the bot with `/start payload` it should return "payload"

**Describe alternatives you've considered**
using `(ctx as any)['startPayload']` works, but it's not

**Comment by Piterden** [comment]
This code shouldn't work, it is incorrect!

**Comment by wojpawlik** [comment]
Fixed: https://github.com/telegraf/telegraf/commit/aa8f0ec4dc9e8ad270a47efc41fd1d69cbbcf185#diff-816fdcd363b86f2b2f141ab2cac15e4fR140

**Comment by MartinSeeler** [comment]
I think this is not fixed properly. I've version 3.38 and the signature is 
```js
/**
 * Registers middleware for handling /start command.
 */
start(...middlewares: ReadonlyArray<Middleware<TContext>>): this
```
