### ISSUE TITLE
tsc build error. error in node_modules/telegraf/typings/session.d.ts

### ISSUE THREAD

**Issue by Danes99** [telegraf/telegraf#1814]
## Context

* Telegraf.js Version: 4.12.2
* Node.js Version: 18.13.0
* Operating System: macosx

## Minimal Example Code Reproducing the Issue

index.ts:
```ts
import { Telegraf } from "telegraf";
```

package.json:
```json
{
  [...]
  "scripts": {
    "build": "tsc -b"
  }
  [...]
}
```

## Expected Behavior

Transpile the TypeScript file to JavaScript file.

## Current Behavior

Build failed.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
> tsc -b

node_modules/telegraf/typings/session.d.ts:40:5 - error TS2416: Property 'set' in type 'MemorySessionStore<T>' is not assignable to the same property in base type 'SessionStore<T>'.
  Type '(name: string, value: T) => void' is not assignable to type '(name: string, value: T) => MaybePromise<{}>'.
    Type 'void' is not assignable to type 'MaybePromise<{}>'.

40     set(name: string, value: T): void;
       ~~~

node_modules/telegraf/typings/session.d.ts:41:5 - error TS2416: Property 'delete' in type 'MemorySessionStore<T>' is not assignable to the same property in base type 'SessionStore<T>'.
  Type '(name: string) => void' is not assignable to type '(name: string) => MaybePromise<{}>'.
    Type 'void' is not assignable to type 'MaybePromise<{}>'.

41     delete(name: string): void;
       ~~~~~~

Found 2 errors.
```

**Comment by MKRhere** [comment]
I'm unable to reproduce this. Can you confirm you're on the latest versions of Telegraf and Typescript? Would you like to make a minimal repro repo?

My attempt:

![image](https://user-images.githubusercontent.com/19621208/225841160-5efd872b-daa8-4679-b335-82a386ad43cb.png)

**Comment by namth0712** [comment]
I got same errors.

"telegraf": "^4.12.2",
"typescript": "^5.0.2"


![image](https://user-images.githubusercontent.com/44791771/226339886-921c1959-80fb-40e7-9c80-18af856c16b3.png)

**Comment by MKRhere** [comment]
@namth0712 I added a commit 54024b21484d7c9372a5bde36f0437bead904bbf to v4. Can you try installing from GitHub:

```TS
npm i github:telegraf/telegraf
```

And see if the issue persists?

**Comment by windok** [comment]
Thanks @MKRhere 
The issue was resolved for me.

"telegraf": "github:telegraf/telegraf",
"typescript": "4.7.4"

**Comment by seb18781** [comment]
I had the same problem. It was resolved with the version from github.

**Comment by Danes99** [comment]
The problem is resolved now with the npm version. Thanks a lot!

**Comment by vitalii-bokhin** [comment]
the problem is not solved
"telegraf": "^4.12.2"
"typescript": "^5.0.3"

**Comment by MKRhere** [comment]
There's a canary version where this must be resolved: [4.12.3-canary.1](https://www.npmjs.com/package/telegraf/v/4.12.3-canary.1). You can install this with `npm i telegraf@canary`. This canary has very minimal changes and should be safe to use. When the next stable release is out, you should upgrade to that.

**Comment by LotharieSlayer** [comment]
It works with canary version but i'm now stuck with this following error. It happens everytime something interact with the bot like sending a message to him for example.
```log
Unhandled error while processing {
  update_id: // The update ID,
  message: {
    // Message object
  }
}
node_modules/telegraf/lib/composer.js:246
                        filter(update)
                        ^

TypeError: filter is not a function
    at predicate (node_modules/telegraf/lib/composer.js:246:25)
    at node_modules/telegraf/lib/composer.js:257:43
    at node_modules/telegraf/lib/composer.js:183:55
    at node_modules/telegraf/lib/composer.js:167:47
    at execute (node_modules/telegraf/lib/composer.js:485:23)
    at node_modules/telegraf/lib/composer.js:486:27
    at node_modules/telegraf/lib/composer.js:161:31
    at execute (node_modules/telegraf/lib/composer.js:485:23)
    at node_modules/telegraf/lib/composer.js:474:20
    at Bot.handleUpdate (node_modules/telegraf/lib/telegraf.js:228:77)
```
My stack :
```json
"dependencies": {
    "telegraf": "^4.12.3-canary.1",
    "ts-node-dev": "^2.0.0",
    "tsc-alias": "^1.8.7"
},
"devDependencies": {
    "typescript": "^5.1.6"
}
```
Can someone help me please ?

EDIT : Forget it, I just missnamed events when calling .on(). It is working.

**Comment by nicolascavallin** [comment]
I've solved it importing as 
`const { Telegraf } = require("telegraf");` 

instead of the modern syntax `import { Telegraf } from "telegraf";`

**Comment by nicolascavallin** [comment]
I've solved it importing as `const { Telegraf } = require("Telegraf");`

The bad thing is you lost the TypeScript code suggestions

**Comment by Skellord** [comment]
I have same problem. My stack: 
```
"devDependencies": {
    "@types/node": "^20.5.6",
    "nodemon": "^3.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "dotenv": "^16.3.1",
    "telegraf": "^4.12.2"
  }
```
